---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: symfony
  namespace: symfony
spec:
  destination:
    namespace: symfony
    server: https://kubernetes.default.svc
  project: default
  source:
    path: Deployment/base
    repoURL: https://github.com/LarsNieuwenhuizen/symfony-dummy.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
