---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: symfony-pr-applicationset
spec:
  generators:
    - pullRequest:
        github:
          owner: LarsNieuwenhuizen
          repo: symfony-dummy
        requeueAfterSeconds: 1800
  template:
    metadata:
      name: 'symfony-pr-{{number}}'
    spec:
      project: default
      source:
        path: 'Deployment/base'
        repoURL: https://github.com/LarsNieuwenhuizen/symfony-dummy.git
        targetRevision: '{{head_sha}}'
        kustomize:
          patches:
            - target:
                kind: IngressRoute
                name: technight-web-route
              patch: |-
                - op: replace
                  path: /spec/routes/0/match
                  value: Host(`pr-{{number}}.technight.developers.nl`)
          images:
          - 'larsnieuwenhuizen/technight-php:pr-{{number}}'
      destination:
        namespace: 'symfony-pr-{{number}}'
        server: https://kubernetes.default.svc
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
