apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: v26.0.0
    helm:
      releaseName: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
